development:
  adapter: postgresql
  encoding: unicode
  database: developers_development
  pool: 5
  username: rahm
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: developers_test
  pool: 5
  username: rahm
  password: 
